= Git Profile Switcher

A terminal-based application written in Kotlin that allows you to switch between multiple Git profiles easily.

== Features

* Manage multiple Git profiles with ease
* Switch between profiles using a simple CLI
* Add, update, and delete profiles
* Automatically generate a default profiles file if it doesn't exist
* No external libraries required

== Requirements

* Kotlin 1.5+
* JDK 8+
* Git

== Installation

=== Using Scoop (Windows)

1. Add the Malefic bucket to Scoop:

+
[source,sh]
----
scoop bucket add malefic https://github.com/OmyDaGreat/MaleficBucket
----

2. Install GitProfileSwitch:

+
[source,sh]
----
scoop install profile
----

== Usage

1. Run the following command to generate a default `.git_profiles.yaml` configuration file in your home directory:

+
[source,sh]
----
profile generate
----

2. Add a new profile:

+
[source,sh]
----
gitprofileswitch add <profileName> <name> <email>
----

3. Switch to a profile:

+
[source,sh]
----
profile switch
----

4. Update an existing profile:

+
[source,sh]
----
profile update <profileName> <newName> <newEmail>
----

5. Delete a profile:

+
[source,sh]
----
profile delete <profileName>
----

6. View the contents of the configuration file:

+
[source,sh]
----
profile view
----

== Configuration File Format

The configuration file uses a YAML format:

[source,yaml]
----
# Git Profiles
personal:
  name: Your Name
  email: your.email@example.com
work:
  name: Work Name
  email: work.email@example.com
----

=== Configuration Options
* `profileName`: The name of the profile
* `name`: The name associated with the profile
* `email`: The email associated with the profile

== Example Configuration File

[source,yaml]
----
personal:
  name: Om Gupta
  email: ogupta4242@gmail.com
malefic:
  name: Malefic
  email: om@malefic.xyz
shawn:
  name: ntnx0246
  email: shawngazin@protonmail.com
----